version: '3.7'
networks:
  front-tier:
  back-tier:
    internal: true
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - back-tier
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 10M
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - back-tier
      - front-tier
volumes:
  db_data: {}
